apiVersion: v2
name: michal-test-chart
description: A Helm chart for Kubernetes
version: 1.0.0
dependencies:
  - name: prometheus
    version: 23.3.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: postgresql
    version: 12.8.2
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
  - name: prometheus-postgres-exporter
    version: 4.8.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus-postgres-exporter.enabled
appVersion: 4.5.6
